### ISSUE TITLE
Unable to find object

### ISSUE THREAD

**Issue by scrwdnet** [hanneskod/libmergepdf#16]
Hi, I'm coming across this intermittent error:

```
iio\libmergepdf\Exception: FPDI: 'Unable to find object (4, 0) at expected location.' in '/home/forge/site/storage/app/files/7d567217-308c-49c5-870d-19222dfa059d.pdf'
```

The file is 100% there at that location, and it's only with certain files others (using the same methods to retrieve the file location) work without any issues. The file itself is fine and opens with no issues when viewing on a computer. I'm not certain this is an issue with libmergepdf but I'm wondering if you have come across this issue before? It's using the Laravel framework for what it is worth.

Great library by the way been super helpful!
Thanks

**Comment by hanneskod** [comment]
Hi scrwdnet and sorry for the late reply!

This issue is related to FPDI (in these cases libmergepdf just wrap the FPDI exceptions. My guess is that this isn't  filesystem related, but that the pdf contains some part that fpdi doesn't understand.. PDF is a weird format after all..

Sorry I couldn't be of more help.
Happy new year =)
