### ISSUE TITLE
Links are removed after merge some of the PDF

### ISSUE THREAD

**Issue by rajenthakur** [hanneskod/libmergepdf#22]
The final PDF contents haven't any link while we merge several PDFs in which some of the PDF content having links. Please have a look.

Thanks
Rajendra

**Comment by hanneskod** [comment]
Hi and thanx for reporting,
this is related to FPDI. Please se https://github.com/Setasign/FPDI.

Hannes

**Comment by hanneskod** [comment]
See https://www.setasign.com/support/faq/fpdi/after-importing-a-page-all-links-are-gone/

**Comment by MIvanIsten** [comment]
_"Since FPDI 2.4.0 link annotations with an URI action are imported if the $importExternalLinks parameter of the [importPage()](https://manuals.setasign.com/fpdi-manual/v2/the-fpdi-class/#c_setasignFpdiFpdiTraitimportPage) method is set to true."_

change the line
https://github.com/hanneskod/libmergepdf/blob/e69826483133bbfbb54b867989018d6cfca2f5b9/src/Driver/Fpdi2Driver.php#L47
to
```php
$template = $fpdi->importPage($pageNr, importExternalLinks: true);
```
or make it configurable on driver
